# Generated by Django 4.2.13 on 2024-07-13 20:44

from django.db import migrations
from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options'),
    ]

    operations = [
        VectorExtension()
    ]
